openapi: 3.0.3
info:
  title: Sample
  description: description
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: local server
paths:
  /users:
    get:
      summary: ユーザー情報取得
      description: ユーザー情報を取得します
      responses:
        '200':
          description: 正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: "object"
                      properties:
                        id:
                          type: "integer"
                          format: "int64"
                          example: 1
                        name:
                          type: "string"
                          example: "test"